/// <reference lib="webworker" />
import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching'
import { clientsClaim } from 'workbox-core'

declare const self: ServiceWorkerGlobalScope

// Take control of all clients immediately when a new SW activates
self.skipWaiting()
clientsClaim()

// Precache all assets generated by Vite (injected at build time by vite-plugin-pwa)
precacheAndRoute(self.__WB_MANIFEST)

// Remove caches left behind by older versions of this SW
cleanupOutdatedCaches()

// ─── Cross-tab sync channel ───────────────────────────────────────
// When any tab writes to IndexedDB it posts a message on this channel.
// All other open tabs receive the message and invalidate their
// TanStack Query cache so they re-fetch and stay in sync.
//
// The channel name is the single source of truth.
// It must match the name used in src/main.tsx exactly.
//
// Message shape:
//   { type: 'IDB_CHANGED', table: string, projectId: string | null }
//
// Nothing in the service worker acts on these messages — it only
// relays them. The tab-side listener in main.tsx handles invalidation.

self.addEventListener('message', (event: ExtendableMessageEvent) => {
  if (event.data && event.data.type === 'IDB_CHANGED') {
    // Broadcast to all other tabs (excluding the sender)
    self.clients.matchAll({ type: 'window' }).then((clients) => {
      clients.forEach((client) => {
        if (client.id !== (event.source instanceof Client ? event.source.id : null)) {
          client.postMessage(event.data)
        }
      })
    })
  }
})
